DROP DATABASE IF EXISTS burgers_db;

CREATE DATABASE burgers_db;

USE burgers_db;

CREATE TABLE IF NOT EXISTS burgers (
id INT NOT NULL AUTO_INCREMENT,
burger_name VARCHAR(150) NOT NULL,
devoured BOOLEAN DEFAULT FALSE NOT NULL,
PRIMARY KEY(id)
);
